name: flutter_chat_demo
description: This is the demo for chat app by Flutter
publish_to: 'none'

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.1
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2
  photo_view: ^0.15.0
  provider: ^6.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - images/

environment:
  sdk: ">=2.17.6 <3.0.0"